package dev.pollito.petclinic_kt_gradle_thymeleaf_tailwind_webpack_htmx_ts.config

import org.springframework.boot.persistence.autoconfigure.EntityScan
import org.springframework.context.annotation.Configuration
import org.springframework.data.jpa.repository.config.EnableJpaRepositories
import org.springframework.transaction.annotation.EnableTransactionManagement

@Configuration
@EntityScan("dev.pollito.petclinic_kt_gradle_thymeleaf_tailwind_webpack_htmx_ts")
@EnableJpaRepositories("dev.pollito.petclinic_kt_gradle_thymeleaf_tailwind_webpack_htmx_ts")
@EnableTransactionManagement
class DomainConfig
